### ISSUE TITLE
Improve CSS for the overlay.

### ISSUE THREAD

**Issue by alphayowakarindi** [OyePriscilla/MyPortfolioSetup#15]
### Highlights

- Great descriptive commits :heavy_check_mark: 
- Correct use of GitHub flow :heavy_check_mark: 
- Linters check passed :heavy_check_mark: 
- Professional README.md :heavy_check_mark: 

### Changes :recycle: 

- We think it would be nice to add the value of the alt attribute of the overlay close icon to improve its accessibility.

**Comment by OyePriscilla** [comment]
Issue resolved. Thanks.
