### ISSUE TITLE
Milestone 5: Portfolio Application Deployment

### ISSUE THREAD

**Issue by OyePriscilla** [OyePriscilla/MyPortfolioSetup#7]
## App Deployment
The application had been deployed earlier; online version can be accessed through this link [PriscillaPortfolio](https://oyepriscilla.github.io/MyPortfolioSetup/)

## ReadMe file updated

**Comment by uwadonat** [comment]
Hi **@OyePriscilla,**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![cong](https://user-images.githubusercontent.com/65860678/172139161-536137c0-5efd-4dec-a409-4bc8bc6931b5.jpg)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
